services:
  db:
    image: postgres:18
    container_name: boojet-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: changemeinprod!

    ports:
      - "5432:5432"

    volumes:
      - boojet_postgres_data:/var/lib/postgresql

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: boojet-app
    restart: unless-stopped

    depends_on:
      db:
        condition: service_healthy

    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: changemeinprod!
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver

    ports:
      - "8080:8080"

volumes:
  boojet_postgres_data: